version: '3.8'

services:
    # AI Services
    llama:
        build:
            context: ./AI/llama
        env_file:
            - ./.env
        volumes:
            - ./AI/llama:/app
        tty: true

    mbti:
        build:
            context: ./AI/mbti
        env_file:
            - ./.env
        volumes:
            - ./AI/mbti:/app
        tty: true

    sentiment:
        build:
            context: ./AI/sentiment
        env_file:
            - ./.env
        volumes:
            - ./AI/sentiment:/app
        tty: true
        environment:
            - HUGGINGFACE_HUB_CACHE=/app/.cache/huggingface
    
    # Users
    mongo_users:
        image: mongo:7.0.8
        volumes:
            - mongo_data_users:/data/db
        ports:
            - 27017:27017
        env_file:
            - ./envs/.env.users
        restart: unless-stopped

    users:
        build:
            context: ./users
        env_file:
            - ./.env
            - ./envs/.env.users
        volumes:
            - ./users:/app
        tty: true
        depends_on:
            - mongo_users

    # Applications        
    mongo_applications:
        image: mongo:7.0.8
        volumes:
            - mongo_data_applications:/data/db
        command: mongod --port 27018
        ports:
            - 27018:27018
        env_file:
            - ./envs/.env.applications
        restart: unless-stopped

    applications:
        build:
            context: ./Applications/applications
        env_file:
            - ./.env
            - ./envs/.env.applications
        volumes:
            - ./Applications/applications:/app
        tty: true
        depends_on:
            - mongo_applications
            - llama
            - mbti
            - sentiment

    mongo_listings:
        image: mongo:7.0.8
        volumes:
            - mongo_data_listings:/data/db
        command: mongod --port 27019
        ports:
            - 27019:27019
        env_file:
            - ./envs/.env.listings
        restart: unless-stopped

    listings:
        build:
            context: ./Applications/listings
        env_file:
            - ./.env
            - ./envs/.env.listings
        volumes:
            - ./Applications/listings:/app
        tty: true
        depends_on:
            - mongo_listings

    # API Gateway
    gateway:
        build: ./nginx/
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        depends_on:
            - users
            - applications
            - listings

volumes:
    mongo_data_users:
    mongo_data_applications:
    mongo_data_listings:
