version: '3.8'

services:
    mongo_users:
        image: mongo:7.0.8
        volumes:
            - mongo_data_users:/data/db
        ports:
            - 27017:27017
        env_file:
            - ./envs/.env.users
        restart: unless-stopped

    users:
        build:
            context: ./users
        env_file:
            - ./.env
            - ./envs/.env.users
        volumes:
            - ./users:/app
        tty: true
        depends_on:
            - mongo_users

    mongo_applications:
        image: mongo:7.0.8
        volumes:
            - mongo_data_applications:/data/db
        command: mongod --port 27018
        ports:
            - 27018:27018
        env_file:
            - ./envs/.env.applications
        restart: unless-stopped

    applications:
        build:
            context: ./applications
        env_file:
            - ./.env
            - ./envs/.env.applications
        volumes:
            - ./applications:/app
        tty: true
        depends_on:
            - mongo_applications


    # AI Services
    llama:
        build:
            context: ./AI/llama
        env_file:
            - ./.env
        volumes:
            - ./AI/llama:/app
        tty: true

    mbti:
        build:
            context: ./AI/mbti
        env_file:
            - ./.env
        volumes:
            - ./AI/mbti:/app
        tty: true

    sentiment:
        build:
            context: ./AI/sentiment
        env_file:
            - ./.env
        volumes:
            - ./AI/sentiment:/app
        tty: true

    nginx:
        build: ./nginx/
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        depends_on:
            - users
            - applications
            - llama
            - mbti
            - sentiment

volumes:
    mongo_data_users:
    mongo_data_applications:
